name: Docker

on:
  release:
    types: [published]
  workflow_dispatch:
  push:

env:
  TEST_TAG: ${{ github.repository }}:test
  DEPLOY_TAGS: ${{ github.repository }}:latest,${{ github.repository }}:${{ github.ref_name }}


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test container starts
        run: |
          set -x
          docker run -d -p8000:8000 --rm --name csp_report_collector ${{ env.TEST_TAG }}
          sleep 1
          curl -vfs localhost:8000/status | grep ok

      ## https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DEPLOY_TAGS }}
